export const warrentyDemoData = {
  dataType: "Warrenty",
  revenue: "2000",
  count: 35,
  expiringCount: 12,
  expiredCount: 4,
  data: [
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: 7696424459,
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "7717359933",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
  ],
};

export const platinumDemoData = {
  dataType: "Platinum",
  revenue: "2000",
  count: 35,
  expiringCount: 12,
  expiredCount: 4,
  data: [
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
  ],
};

export const goldDemoData = {
  dataType: "Gold",
  revenue: "2000",
  count: 35,
  expiringCount: 12,
  expiredCount: 4,
  data: [
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
  ],
};

export const silverDemoData = {
  dataType: "Silver",
  revenue: "2000",
  count: 35,
  expiringCount: 12,
  expiredCount: 4,
  data: [
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: true,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
    {
      name: "Arjun Rawat",
      number: "1234567890",
      jon: "202100",
      address: "Address Address, Address Address",
      isExpired: false,
    },
  ],
};
