name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/workspace/frontend || exit 1

            # Save any local changes to the stash
            git stash push -m "Saving local changes before deployment"
            
            # Ensure repository is up to date
            git reset --hard origin/main
            git pull origin main

            # Apply stashed changes if any
            git stash apply || echo "No stashed changes to apply"

            # Install dependencies locally
            /home/ubuntu/.nvm/versions/node/v21.7.1/bin/npm install
            /home/ubuntu/.nvm/versions/node/v21.7.1/bin/npm run build
            

            # Restart application with pm2
            /home/ubuntu/.nvm/versions/node/v21.7.1/bin/pm2 restart static-page-server-3000
          EOF
        shell: bash
